// Generated by CodiumAI

import { render, screen } from '@testing-library/react';
import { describe, expect, it } from 'vitest';
import App from '../App';

describe('App', () => {
  // Test that the App component renders the Header component
  it('should render the Header component', () => {
    // ARRANGE
    render(<App />);

    // ASSERT
    expect(screen.getByRole('banner')).toBeInTheDocument();
  });
});
