// Generated by CodiumAI

import { render } from '@testing-library/react';
import { describe, expect, it } from 'vitest';
import { Header } from '../../../components/Header';
import { listHeader } from '../../../utils';

describe('Header', () => {
  // Tests that the navigation bar displays all the expected items
  it('should display all navigation items', () => {
    // Arrange
    const expectedNavList = Object.keys(listHeader);

    // Act
    const wrapper = render(<Header />);

    // Assert
    expect(wrapper.getAllByRole('button')).toHaveLength(expectedNavList.length);
  });
});
